// packages/pixi/src/solid/application.tsx
import { Application as PixiApplication } from "pixi.js";
import type { ParentProps } from "solid-js";
import { createResource, onCleanup, onMount } from "solid-js";
import { Engine } from "../engine/engine";
import { ApplicationContext, EngineContext, ParentContext } from "./context";

export function Application(props: ParentProps) {
  const canvas = document.createElement("canvas");
  const engine = new Engine(canvas);
  const app = new PixiApplication();

  const [initResource] = createResource(async () => {
    await app.init({ antialias: true, roundPixels: true, canvas });
    onCleanup(() => app.destroy(undefined, { children: true }));
    return true;
  });

  onMount(() => engine.start());
  onCleanup(() => engine.stop());

  return (
    <>
      {canvas}
      {initResource() && (
        <ApplicationContext.Provider value={app}>
          <EngineContext.Provider value={engine}>
            <ParentContext.Provider value={app.stage}>
              {props.children}
            </ParentContext.Provider>
          </EngineContext.Provider>
        </ApplicationContext.Provider>
      )}
    </>
  );
}

// packages/pixi/src/react/Application.tsx
import { Application as PixiApplication } from "pixi.js";
import type { ReactNode } from "react";
import { createContext, useEffect, useState } from "react";
import { Engine } from "../engine";

export interface ApplicationProps {
  resizeTo?: HTMLDivElement | null;
  children?: ReactNode;
}

export function Application({ resizeTo, children }: ApplicationProps) {
  const [container, setContainer] = useState<HTMLDivElement | null>(null);
  const [app, setApp] = useState<PixiApplication>();

  useEffect(() => {
    if (!container) {
      return;
    }

    const canvas = document.createElement("canvas");
    Engine.replace(canvas);

    const app = new PixiApplication();

    container.appendChild(canvas);

    const initPromise = app.init({
      antialias: true,
      roundPixels: true,
      resizeTo: resizeTo ?? undefined,
      canvas,
    });

    void initPromise.then(() => {
      app.stage.interactive = true;
      setApp(app);
    });

    return () => {
      Engine.instance.stop();
      canvas.remove();
      void initPromise.then(() => {
        app.destroy(undefined, { children: true });
      });
    };
  }, [container, resizeTo]);

  return (
    <>
      <div ref={setContainer} />
      {app && (
        <ApplicationContext.Provider value={app}>
          {children}
        </ApplicationContext.Provider>
      )}
    </>
  );
}

export const ApplicationContext = createContext<PixiApplication>(
  new Proxy({} as PixiApplication, {
    get() {
      throw new Error("ApplicationContext not provided");
    },
  }),
);
