// packages/pixi/src/solid/Stage.tsx
import type { Accessor, ParentComponent } from "solid-js";
import { createEffect, useContext } from "solid-js";
import type { Matrix } from "@mp/math";
import { Matrix as PixiMatrix } from "pixi.js";
import { ApplicationContext } from "./Application";
import { ContainerContext } from "./ContainerContext";

export interface StageProps {
  matrix?: Accessor<Matrix>;
}

export const Stage: ParentComponent<StageProps> = (props) => {
  const app = useContext(ApplicationContext);

  createEffect(() => {
    const m = props.matrix?.();
    if (m) {
      app.stage.setFromMatrix(new PixiMatrix(...m.data));
    }
  });

  return (
    <ContainerContext.Provider value={app.stage}>
      {props.children}
    </ContainerContext.Provider>
  );
};

// packages/pixi/src/react/Stage.tsx
import type { ReactNode } from "react";
import { useContext, useEffect } from "react";
import type { Matrix } from "@mp/math";
import { Matrix as PixiMatrix } from "pixi.js";
import { ApplicationContext } from "./Application";
import { ContainerContext } from "./Pixi";

export interface StageProps {
  matrix?: Matrix;
  children?: ReactNode;
}

export function Stage({ children, matrix }: StageProps) {
  const app = useContext(ApplicationContext);

  useEffect(() => {
    if (matrix) {
      app.stage.setFromMatrix(new PixiMatrix(...matrix.data));
    }
  }, [app, matrix]);

  return (
    <ContainerContext.Provider value={app.stage}>
      {children}
    </ContainerContext.Provider>
  );
}
